# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-lb-http-backend
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: HTTP Load balancer backend module
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-lb-http.git
      sourceType: git
      dir: /modules/backend
    version: 12.1.0
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
  content:
    examples:
      - name: cdn-policy
        location: examples/cdn-policy
      - name: certificate-map
        location: examples/certificate-map
      - name: cloudrun
        location: examples/cloudrun
      - name: cloudrun-implicit-serverless-neg
        location: examples/cloudrun-implicit-serverless-neg
      - name: cross-project-mig-backend
        location: examples/cross-project-mig-backend
      - name: dynamic-backend
        location: examples/dynamic-backend
      - name: gke-node-port
        location: examples/https-gke/gke-node-port
      - name: https-gke
        location: examples/https-gke
      - name: https-redirect
        location: examples/https-redirect
      - name: lb-http-separate-frontend-and-backend
        location: examples/lb-http-separate-frontend-and-backend
      - name: mig-nat-http-lb
        location: examples/mig-nat-http-lb
      - name: multi-backend-multi-mig-bucket-https-lb
        location: examples/multi-backend-multi-mig-bucket-https-lb
      - name: multi-mig-http-lb
        location: examples/multi-mig-http-lb
      - name: multiple-certs
        location: examples/multiple-certs
      - name: shared-vpc
        location: examples/shared-vpc
      - name: traffic-director
        location: examples/traffic-director
      - name: user-managed-google-managed-ssl
        location: examples/user-managed-google-managed-ssl
  interfaces:
    variables:
      - name: name
        description: Name for the backend service.
        varType: string
        required: true
      - name: project_id
        description: The project to deploy to, if not set the default provider project is used.
        varType: string
        required: true
      - name: load_balancing_scheme
        description: Load balancing scheme type (EXTERNAL for classic external load balancer, EXTERNAL_MANAGED for Envoy-based load balancer, and INTERNAL_SELF_MANAGED for traffic director).
        varType: string
        defaultValue: EXTERNAL_MANAGED
      - name: protocol
        description: The protocol this BackendService uses to communicate with backends.
        varType: string
        defaultValue: HTTP
      - name: port_name
        description: Name of backend port. The same name should appear in the instance groups referenced by this service. Required when the load balancing scheme is EXTERNAL.
        varType: string
        defaultValue: http
      - name: description
        description: Description of the backend service.
        varType: string
      - name: enable_cdn
        description: Enable Cloud CDN for this BackendService.
        varType: bool
        defaultValue: false
      - name: compression_mode
        description: Compress text responses using Brotli or gzip compression.
        varType: string
        defaultValue: DISABLED
      - name: custom_request_headers
        description: Headers that the HTTP/S load balancer should add to proxied requests.
        varType: list(string)
        defaultValue: []
      - name: custom_response_headers
        description: Headers that the HTTP/S load balancer should add to proxied responses.
        varType: list(string)
        defaultValue: []
      - name: connection_draining_timeout_sec
        description: Time for which instance will be drained (not accept new connections, but still work to finish started).
        varType: number
      - name: session_affinity
        description: "Type of session affinity to use. Possible values are: NONE, CLIENT_IP, CLIENT_IP_PORT_PROTO, CLIENT_IP_PROTO, GENERATED_COOKIE, HEADER_FIELD, HTTP_COOKIE, STRONG_COOKIE_AFFINITY."
        varType: string
      - name: affinity_cookie_ttl_sec
        description: Lifetime of cookies in seconds if session_affinity is GENERATED_COOKIE.
        varType: number
      - name: locality_lb_policy
        description: The load balancing algorithm used within the scope of the locality.
        varType: string
      - name: timeout_sec
        description: This has different meaning for different type of load balancing. Please refer https://cloud.google.com/load-balancing/docs/backend-service#timeout-setting
        varType: number
      - name: log_config
        description: This field denotes the logging options for the load balancer traffic served by this backend service. If logging is enabled, logs will be exported to Stackdriver.
        varType: |-
          object({
              enable      = bool
              sample_rate = number
            })
        defaultValue:
          enable: true
          sample_rate: 1
      - name: groups
        description: The list of backend instance group which serves the traffic.
        varType: |-
          list(object({
              group       = string
              description = optional(string)

              balancing_mode               = optional(string)
              capacity_scaler              = optional(number)
              max_connections              = optional(number)
              max_connections_per_instance = optional(number)
              max_connections_per_endpoint = optional(number)
              max_rate                     = optional(number)
              max_rate_per_instance        = optional(number)
              max_rate_per_endpoint        = optional(number)
              max_utilization              = optional(number)
            }))
        defaultValue: []
        connections:
        - source:
            source: github.com/terraform-google-modules/terraform-google-vm//modules/mig
            version: ~> 12.0
          spec:
            outputExpr: '{"group": instance_group}'
      - name: serverless_neg_backends
        description: The list of serverless backend which serves the traffic.
        varType: |-
          list(object({
              region          = string
              type            = string // cloud-run, cloud-function, and app-engine
              service_name    = string
              service_version = optional(string)
            }))
        defaultValue: []
        connections:
        - source:
            source: github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2
            version: ~> 0.13
          spec:
            outputExpr: '{"region": location, "service_name": service_name, "type": "cloud-run", "service_version": ""}'
      - name: iap_config
        description: Settings for enabling Cloud Identity Aware Proxy Structure.
        varType: |-
          object({
              enable               = bool
              oauth2_client_id     = optional(string)
              oauth2_client_secret = optional(string)
            })
        defaultValue:
          enable: false
      - name: cdn_policy
        description: Cloud CDN configuration for this BackendService.
        varType: |-
          object({
              cache_mode                      = optional(string)
              signed_url_cache_max_age_sec    = optional(string)
              default_ttl                     = optional(number)
              max_ttl                         = optional(number)
              client_ttl                      = optional(number)
              negative_caching                = optional(bool)
              serve_while_stale               = optional(number)
              bypass_cache_on_request_headers = optional(list(string))
              negative_caching_policy = optional(object({
                code = optional(number)
                ttl  = optional(number)
              }))
              cache_key_policy = optional(object({
                include_host           = optional(bool)
                include_protocol       = optional(bool)
                include_query_string   = optional(bool)
                query_string_blacklist = optional(list(string))
                query_string_whitelist = optional(list(string))
                include_http_headers   = optional(list(string))
                include_named_cookies  = optional(list(string))
              }))
            })
        defaultValue: {}
      - name: outlier_detection
        description: Settings controlling eviction of unhealthy hosts from the load balancing pool.
        varType: |-
          object({
              base_ejection_time = optional(object({
                seconds = number
                nanos   = optional(number)
              }))
              consecutive_errors                    = optional(number)
              consecutive_gateway_failure           = optional(number)
              enforcing_consecutive_errors          = optional(number)
              enforcing_consecutive_gateway_failure = optional(number)
              enforcing_success_rate                = optional(number)
              interval = optional(object({
                seconds = number
                nanos   = optional(number)
              }))
              max_ejection_percent        = optional(number)
              success_rate_minimum_hosts  = optional(number)
              success_rate_request_volume = optional(number)
              success_rate_stdev_factor   = optional(number)
            })
      - name: health_check
        description: Input for creating HttpHealthCheck or HttpsHealthCheck resource for health checking this BackendService. A health check must be specified unless the backend service uses an internet or serverless NEG as a backend.
        varType: |-
          object({
              host                = optional(string, null)
              request_path        = optional(string, null)
              request             = optional(string, null)
              response            = optional(string, null)
              port                = optional(number, null)
              port_name           = optional(string, null)
              proxy_header        = optional(string, null)
              port_specification  = optional(string, null)
              protocol            = optional(string, null)
              check_interval_sec  = optional(number, 5)
              timeout_sec         = optional(number, 5)
              healthy_threshold   = optional(number, 2)
              unhealthy_threshold = optional(number, 2)
              logging             = optional(bool, false)
            })
      - name: edge_security_policy
        description: The resource URL for the edge security policy to associate with the backend service
        varType: string
      - name: security_policy
        description: The resource URL for the security policy to associate with the backend service
        varType: string
      - name: host_path_mappings
        description: The list of host/path for which traffic could be sent to the backend service
        varType: |-
          list(object({
              host = string
              path = string
            }))
        defaultValue:
          - host: "*"
            path: /*
      - name: firewall_networks
        description: Names of the networks to create firewall rules in
        varType: list(string)
        defaultValue:
          - default
      - name: firewall_projects
        description: Names of the projects to create firewall rules in
        varType: list(string)
        defaultValue:
          - default
      - name: target_tags
        description: List of target tags for health check firewall rule. Exactly one of target_tags or target_service_accounts should be specified.
        varType: list(string)
        defaultValue: []
      - name: target_service_accounts
        description: List of target service accounts for health check firewall rule. Exactly one of target_tags or target_service_accounts should be specified.
        varType: list(string)
        defaultValue: []
    outputs:
      - name: backend_service_info
        description: Host, path and backend service mapping
        type:
          - list
          - - object
            - host: string
              path: string
              backend_service: string
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
          - roles/storage.admin
      - level: Project
        roles:
          - roles/compute.xpnAdmin
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
      - compute.googleapis.com
      - run.googleapis.com
      - iam.googleapis.com
      - certificatemanager.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 6.0, < 7"
      - source: hashicorp/google-beta
        version: ">= 6.0, < 7"
      - source: hashicorp/random
        version: ">= 2.1"
